version: '3'

services:
  db:
    image: mysql
    container_name: db
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql


  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/wordpress


  webserver:
    depends_on:
      - wordpress
    image: ubuntu/nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs


volumes:
  wordpress:
  dbdata:
