version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'


  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html


  webserver:
    depends_on:
      - wordpress
    image: ubuntu/nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs


volumes:
  wordpress:
  dbdata:
